-- Reverse of 0001_core_schema.up.sql
DROP TRIGGER IF EXISTS trg_inv_mov_company_guard    ON inventory_movements;
DROP TRIGGER IF EXISTS trg_plan_headers_status_guard ON plan_headers;
DROP TRIGGER IF EXISTS trg_plan_items_status_guard   ON plan_items;
DROP FUNCTION IF EXISTS fn_movement_company_guard();
DROP FUNCTION IF EXISTS fn_plan_status_guard();

DROP TABLE IF EXISTS dd_fields;
DROP TABLE IF EXISTS dd_tables;
DROP TABLE IF EXISTS dd_value_helps;
DROP TABLE IF EXISTS dd_domains;
DROP TABLE IF EXISTS audit_log;
DROP TABLE IF EXISTS number_ranges;
DROP TABLE IF EXISTS inventory_balances;
DROP TABLE IF EXISTS inventory_movements;
DROP TABLE IF EXISTS actual_items;
DROP TABLE IF EXISTS actual_headers;
DROP TABLE IF EXISTS plan_items;
DROP TABLE IF EXISTS plan_headers;
DROP TABLE IF EXISTS planning_versions;
DROP TABLE IF EXISTS seasons;
DROP TABLE IF EXISTS movement_types;
DROP TABLE IF EXISTS process_materials;
DROP TABLE IF EXISTS processes;
DROP TABLE IF EXISTS production_lines;
DROP TABLE IF EXISTS warehouse_materials;
DROP TABLE IF EXISTS warehouses;
DROP TABLE IF EXISTS packaging_types;
DROP TABLE IF EXISTS company_materials;
DROP TABLE IF EXISTS materials;
DROP TABLE IF EXISTS uom_conversions;
DROP TABLE IF EXISTS uoms;
DROP TABLE IF EXISTS refresh_tokens;
DROP TABLE IF EXISTS user_company_roles;
DROP TABLE IF EXISTS user_companies;
DROP TABLE IF EXISTS role_permissions;
DROP TABLE IF EXISTS permissions;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS companies;
