package controller

import (
	"time"

	"github.com/gin-gonic/gin"

	"github.com/Sovanna2011/SugarProductionPlannningV1/backend/internal/dto"
	"github.com/Sovanna2011/SugarProductionPlannningV1/backend/internal/mapper"
	"github.com/Sovanna2011/SugarProductionPlannningV1/backend/internal/model"
	"github.com/Sovanna2011/SugarProductionPlannningV1/backend/internal/repository/interfaces"
	"github.com/Sovanna2011/SugarProductionPlannningV1/backend/internal/service"
)

type InventoryController struct {
	inventory *service.InventoryService
}

func NewInventoryController(inventory *service.InventoryService) *InventoryController {
	return &InventoryController{inventory: inventory}
}

func (ctl *InventoryController) ListMovements(c *gin.Context) {
	companyID := CompanyID(c)
	opts, ok := ListOptions(c, &companyID)
	if !ok {
		return
	}

	filter := interfaces.MovementFilter{DocumentNo: c.Query("documentNo")}
	var valid bool
	if filter.WarehouseID, valid = QueryID(c, "warehouseId"); !valid {
		return
	}
	if filter.MaterialID, valid = QueryID(c, "materialId"); !valid {
		return
	}
	if filter.MovementTypeID, valid = QueryID(c, "movementTypeId"); !valid {
		return
	}
	if filter.From, valid = QueryDate(c, "dateFrom"); !valid {
		return
	}
	if filter.To, valid = QueryDate(c, "dateTo"); !valid {
		return
	}

	page, err := ctl.inventory.ListMovements(c.Request.Context(), opts, filter)
	if err != nil {
		Fail(c, err)
		return
	}
	Paged(c, mapper.Slice(page.Rows, mapper.MovementToDTO), opts, page.Total)
}

// CreateMovement records a manual correction. Production movements are not
// created here — they are generated by posting an actual document.
func (ctl *InventoryController) CreateMovement(c *gin.Context) {
	req, ok := Bind[dto.MovementRequest](c)
	if !ok {
		return
	}
	movements, err := ctl.inventory.Adjust(c.Request.Context(), service.MovementRequest{
		CompanyID:       CompanyID(c),
		TransactionDate: req.TransactionDate.Time,
		MaterialID:      req.MaterialID,
		WarehouseID:     req.WarehouseID,
		MovementTypeID:  req.MovementTypeID,
		PackagingTypeID: req.PackagingTypeID,
		ProcessID:       req.ProcessID,
		Quantity:        req.Quantity,
		UOMID:           req.UOMID,
		SourceModule:    model.SourceModuleManual,
		Remark:          req.Remark,
	})
	if err != nil {
		Fail(c, err)
		return
	}
	Created(c, mapper.Slice(movements, mapper.MovementToDTO))
}

// Transfer writes the linked OUT and IN pair. Both stay inside one company —
// a cross-company transfer is rejected with E-VAL-010 (§34).
func (ctl *InventoryController) Transfer(c *gin.Context) {
	req, ok := Bind[dto.TransferRequest](c)
	if !ok {
		return
	}
	movements, err := ctl.inventory.Transfer(c.Request.Context(), service.TransferRequest{
		CompanyID:       CompanyID(c),
		FromWarehouseID: req.FromWarehouseID,
		ToWarehouseID:   req.ToWarehouseID,
		MaterialID:      req.MaterialID,
		PackagingTypeID: req.PackagingTypeID,
		Quantity:        req.Quantity,
		UOMID:           req.UOMID,
		TransactionDate: req.TransactionDate.Time,
		Remark:          req.Remark,
	})
	if err != nil {
		Fail(c, err)
		return
	}
	Created(c, mapper.Slice(movements, mapper.MovementToDTO))
}

func (ctl *InventoryController) ReverseMovement(c *gin.Context) {
	id, ok := PathID(c, "id")
	if !ok {
		return
	}
	req, ok := Bind[dto.ReverseRequest](c)
	if !ok {
		return
	}
	movement, err := ctl.inventory.Reverse(c.Request.Context(), CompanyID(c), id, req.Remark)
	if err != nil {
		Fail(c, err)
		return
	}
	Created(c, mapper.MovementToDTO(*movement))
}

func (ctl *InventoryController) Balances(c *gin.Context) {
	warehouseID, ok := QueryID(c, "warehouseId")
	if !ok {
		return
	}
	materialID, ok := QueryID(c, "materialId")
	if !ok {
		return
	}
	asOf, ok := ctl.asOfDate(c)
	if !ok {
		return
	}

	rows, err := ctl.inventory.Balances(c.Request.Context(), CompanyID(c),
		warehouseID, materialID, asOf)
	if err != nil {
		Fail(c, err)
		return
	}
	OK(c, mapper.Slice(rows, mapper.BalanceToDTO))
}

// Capacity implements §F5, including the traffic-light bands.
func (ctl *InventoryController) Capacity(c *gin.Context) {
	warehouseID, ok := QueryID(c, "warehouseId")
	if !ok {
		return
	}
	asOf, ok := ctl.asOfDate(c)
	if !ok {
		return
	}

	statuses, err := ctl.inventory.Capacity(c.Request.Context(), CompanyID(c), warehouseID, asOf)
	if err != nil {
		Fail(c, err)
		return
	}
	OK(c, mapper.Slice(statuses, mapper.CapacityToDTO))
}

// Reconcile runs the balance reconciliation of B3 on demand; the same entry
// point is what the nightly job calls.
func (ctl *InventoryController) Reconcile(c *gin.Context) {
	from, ok := RequiredQueryDate(c, "dateFrom")
	if !ok {
		return
	}
	to, ok := RequiredQueryDate(c, "dateTo")
	if !ok {
		return
	}
	companyID := CompanyID(c)

	discrepancies, err := ctl.inventory.Reconcile(c.Request.Context(), companyID, from, to)
	if err != nil {
		Fail(c, err)
		return
	}
	OK(c, dto.ReconcileResponse{
		CompanyID:     companyID,
		DateFrom:      dto.NewDate(from),
		DateTo:        dto.NewDate(to),
		Discrepancies: mapper.Slice(discrepancies, mapper.DiscrepancyToDTO),
	})
}

// asOfDate defaults the balance cut-off to today when the caller does not name
// one.
func (ctl *InventoryController) asOfDate(c *gin.Context) (time.Time, bool) {
	raw := c.Query("asOfDate")
	if raw == "" {
		now := time.Now().UTC()
		return time.Date(now.Year(), now.Month(), now.Day(), 0, 0, 0, 0, time.UTC), true
	}
	parsed, err := dto.ParseDate(raw)
	if err != nil {
		Fail(c, err)
		return time.Time{}, false
	}
	return parsed, true
}
